
all:
	make -C example_01 all
	make -C example_02 all
	make -C example_03 all

clean:
	make -C example_01 clean
	make -C example_02 clean
	make -C example_03 clean

check:
	make -C example_01 check
	make -C example_02 check
	make -C example_03 check

