
all:
	make -C perl all
	make -C python all
	make -C ruby all

clean:
	make -C perl clean
	make -C python clean
	make -C ruby clean

check:
	make -C perl check
	make -C python check
	make -C ruby check

