# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package holder;
use base qw(Exporter);
use base qw(DynaLoader);
package holderc;
bootstrap holder;
package holder;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package holder;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package holder;


############# Class : holder::Object ##############

package holder::Object;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( holder );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = holderc::new_Object(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        holderc::delete_Object($self);
        delete $OWNER{$self};
    }
}

*setText = *holderc::Object_setText;
*getText = *holderc::Object_getText;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : holder::ObjectHolder ##############

package holder::ObjectHolder;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( holder );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = holderc::new_ObjectHolder(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        holderc::delete_ObjectHolder($self);
        delete $OWNER{$self};
    }
}

*setObject = *holderc::ObjectHolder_setObject;
*getObject = *holderc::ObjectHolder_getObject;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package holder;

1;
